"""Finalize WITECK Shared Dual-Head release without __pycache__/manifest drift.

Key fix versus v1.1.0:
1) Copy and configure release.
2) Run smoke test.
3) REMOVE __pycache__ and *.pyc.
4) Build manifest hashes AFTER cleanup.
5) ZIP with an explicit cache exclusion rule.

This guarantees that bytecode generated by the smoke test is not part of the
release and cannot invalidate manifest verification.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

import torch


RELEASE_NAME = "WITECK_AI_RELEASE_SHARED_DUAL_HEAD_v1.1.1"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def as_list(value):
    return value.tolist() if hasattr(value, "tolist") else value


def remove_python_cache(root: Path):
    for cache_dir in list(root.rglob("__pycache__")):
        if cache_dir.is_dir():
            shutil.rmtree(cache_dir, ignore_errors=True)
    for pyc in list(root.rglob("*.pyc")):
        try:
            pyc.unlink()
        except FileNotFoundError:
            pass


def release_files(root: Path):
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        if "__pycache__" in path.parts:
            continue
        if path.suffix.lower() == ".pyc":
            continue
        yield path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--checkpoint",
        default=r"output\shared_dual_head\seed_40\shared_dual_head.pt",
    )
    ap.add_argument("--template-dir", default="ai_release")
    ap.add_argument(
        "--output-dir",
        default=r"release\shared_dual_head_v1.1.1",
    )
    ap.add_argument(
        "--relaxed-json",
        default=None,
        help="relaxed_thresholds.json produced by calibrate_relaxed_thresholds.py",
    )
    ap.add_argument("--skip-smoke-test", action="store_true")
    args = ap.parse_args()

    checkpoint_path = Path(args.checkpoint).resolve()
    template_dir = Path(args.template_dir).resolve()
    out_root = Path(args.output_dir).resolve()
    package_dir = out_root / "ai_release"
    weights_dir = package_dir / "weights"

    if not checkpoint_path.exists():
        raise FileNotFoundError(f"Checkpoint not found: {checkpoint_path}")
    if not template_dir.exists():
        raise FileNotFoundError(f"Template not found: {template_dir}")

    ckpt = torch.load(checkpoint_path, map_location="cpu", weights_only=False)

    if out_root.exists():
        shutil.rmtree(out_root)
    shutil.copytree(
        template_dir,
        package_dir,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )

    weights_dir.mkdir(parents=True, exist_ok=True)
    placeholder = weights_dir / "PUT_NEW_CHECKPOINT_HERE.txt"
    if placeholder.exists():
        placeholder.unlink()

    release_weight = weights_dir / "shared_dual_head_v1.pt"
    shutil.copy2(checkpoint_path, release_weight)

    # Exact normalization from checkpoint.
    preprocess_path = package_dir / "preprocess.json"
    preprocess = json.loads(preprocess_path.read_text(encoding="utf-8"))
    preprocess["model_version"] = "shared-dual-head-v1.1.1"
    preprocess["dual_head"] = {
        "sequence_mean": as_list(ckpt["sequence_mean"]),
        "sequence_std": as_list(ckpt["sequence_std"]),
        "duration_mean": float(ckpt["duration_mean"]),
        "duration_std": float(ckpt["duration_std"]),
    }
    preprocess["checkpoint"] = {
        "seed": ckpt.get("seed", 40),
        "train_users": ckpt.get("train_users", []),
        "unseen_users": ckpt.get("unseen_users", []),
    }
    preprocess_path.write_text(
        json.dumps(preprocess, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    # Thresholds.
    thresholds_path = package_dir / "thresholds.json"
    thresholds = json.loads(thresholds_path.read_text(encoding="utf-8"))
    thresholds["release"] = "shared-dual-head-v1.1.1"
    thresholds["selected_operating_point"] = "default"
    thresholds["operating_points"]["default"] = {
        "gesture_threshold": float(ckpt["gesture_threshold"]),
        "user_threshold": float(ckpt["user_threshold"]),
        "source": "known-user validation calibration from packaged checkpoint",
    }

    if args.relaxed_json:
        relaxed_data = json.loads(
            Path(args.relaxed_json).read_text(encoding="utf-8")
        )
        if relaxed_data.get("final_test_users_used") is not False:
            raise ValueError(
                "Refusing relaxed thresholds without explicit "
                "final_test_users_used=false provenance."
            )
        relaxed = relaxed_data["demo_relaxed"]
        thresholds["operating_points"]["demo_relaxed"] = {
            "gesture_threshold": float(relaxed["gesture_threshold"]),
            "user_threshold": float(relaxed["user_threshold"]),
            "source": "known-user validation only",
            "gesture_validation_far": float(
                relaxed["gesture_validation_far"]
            ),
            "gesture_validation_frr": float(
                relaxed["gesture_validation_frr"]
            ),
            "user_validation_far": float(
                relaxed["user_validation_far"]
            ),
            "user_validation_frr": float(
                relaxed["user_validation_frr"]
            ),
        }
        thresholds["demo_relaxed"] = {
            "status": "CALIBRATED",
            "provenance": "known-user validation only",
        }

    thresholds_path.write_text(
        json.dumps(thresholds, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    # Remove template manifest before smoke test. A final manifest is created later.
    manifest_path = package_dir / "manifest.json"
    if manifest_path.exists():
        manifest_path.unlink()

    # Smoke test FIRST.
    if not args.skip_smoke_test:
        print("Running smoke test...")
        proc = subprocess.run(
            [sys.executable, str(package_dir / "smoke_test.py")],
            cwd=str(package_dir),
            check=False,
        )
        if proc.returncode != 0:
            raise RuntimeError("Smoke test failed; release not created.")

    # Critical fix: discard bytecode generated by smoke test.
    remove_python_cache(package_dir)

    # Manifest AFTER smoke test and cleanup.
    entries = []
    for path in release_files(package_dir):
        if path.name == "manifest.json":
            continue
        entries.append(
            {
                "path": str(path.relative_to(package_dir)).replace("\\", "/"),
                "bytes": path.stat().st_size,
                "sha256": sha256(path),
            }
        )

    manifest = {
        "release": "shared-dual-head-v1.1.1",
        "status": "FINALIZED",
        "created_from_checkpoint": str(checkpoint_path),
        "architecture": (
            "hand-only shared two-stream 1D-CNN + gesture/user embedding heads"
        ),
        "embedding_dim": 128,
        "input_contract": {
            "raw": "MediaPipe Hand landmarks",
            "sequence_length": 32,
            "feature_dim": 127,
            "right_hand_only": True,
        },
        "threading": {
            "internal_rlock": True,
            "backend_model_forward_lock_required": False,
        },
        "matching": {
            "owner": "backend",
            "similarity": "cosine",
            "policy": "one gesture template + one user template per user",
        },
        "python_bytecode": {
            "included": False,
            "rule": "__pycache__ and *.pyc excluded from manifest and ZIP",
        },
        "files": entries,
    }
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    # ZIP only stable release files.
    zip_path = out_root / f"{RELEASE_NAME}.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in release_files(package_dir):
            zf.write(
                path,
                Path("ai_release") / path.relative_to(package_dir),
            )

    print()
    print("FINALIZED release created")
    print("folder:", package_dir)
    print("zip:   ", zip_path)
    print("__pycache__/pyc included: NO")


if __name__ == "__main__":
    main()
